### ISSUE TITLE
social media links

### ISSUE THREAD

**Issue by yupitstate** [alexG53090/tateTucker#2]
make sure they click through to accurate sites.

**Comment by yupitstate** [comment]
emailed links to make easier:

soundcloud: soundcloud.com/tatetucker

facebook: facebook.com/tatetucker

twitter: twitter.com/yupitstate

youtube: youtube.com/tatetucker

instagram: instagram.com/yupitstate 

tumblr: http://tatetucker.tumblr.com/

**Comment by alexUXUI** [comment]
check!
